### PR TITLE
Storage Icon

### PR DESCRIPTION
**Pull request by srt10coupe**
Display the correct icon, not the 'cloud' icon.

### CODE REVIEW

**Comment by srt10coupe** [comment]
Screenshot_20190421-003817

**Review by Offerel — APPROVED** [review]
Many thx for that pull request. Will be included in the next release.

**Comment by bduijnhouwer** [comment]
Good morning, 

I just updated roundcube_storage and now the storage doesn't load at
all...
The screen just goes blank. I tried this with both Internet Explorer and
Firefox. 

This happens now in all the templates, classic, larry and elastic. 

So the change you made, only made it worse. ;-) 

-- 

Met vriendelijke groet,

BASTIAAN DUIJNHOUWER 

Distelvlinder 9, 2317 JX  Leiden 
M 06-19344358 

Offerel schreef op 25-04-2019 21:53:

> Merged #6 [1] into master. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/Offerel/roundcube_storage/pull/6
[2] https://github.com/Offerel/roundcube_storage/pull/6#event-2301309801
[3]

**Comment by bduijnhouwer** [comment]
Good morning, 

When updating, my config.inc.php was gone.
That was the reason it didn't load. 

After making a new config.inc.php everything worked fine! 

In all the different themes, so I'm very grateful you fixed this for me
!! 

-- 

Met vriendelijke groet,

BASTIAAN DUIJNHOUWER 

Distelvlinder 9, 2317 JX  Leiden 
M 06-19344358 

Offerel schreef op 25-04-2019 21:53:

> Merged #6 [1] into master. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/Offerel/roundcube_storage/pull/6
[2] https://github.com/Offerel/roundcube_storage/pull/6#event-2301309801
[3]

**Comment by bduijnhouwer** [comment]
Hi, 

I'm so sorry to spam you like this, but I found another little problem.
In your new version (1.4.1) there is this file :
"/plugins/storage/elfinder/elopen.html" missing. 

In the other version (1.4.0) this file does exists. So, whenever I want
to add an attachment from within composing a new mail, I get a 404
error.

When I copy this file manually from the old version to the new version,
everything works again. 

-- 

Met vriendelijke groet,

BASTIAAN DUIJNHOUWER 

Distelvlinder 9, 2317 JX  Leiden 
M 06-19344358 

Offerel schreef op 25-04-2019 21:53:

> Merged #6 [1] into master. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/Offerel/roundcube_storage/pull/6
[2] https://github.com/Offerel/roundcube_storage/pull/6#event-2301309801
[3]

**Comment by Offerel** [comment]
Ahh right, I'm afraid the file is missing. I had to create a completely new directory to make sure that the new elFinder version is complete and works without the security vulnerabilities of the old version (including 2.1.48). I create a new release and add the missing file there. In the dev version the file is not longer needed, so I missed it here. Sorry.

**Pull request merged**
